{% set name = "sqlfluff" %}
{% set version = "4.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ee2bcd5d704d0bef56bf80b8f0da9b519ab3e9e0bb1d5e6e4b7e3944d3f5606

build:
  number: 0
  entry_points:
    - sqlfluff = sqlfluff.cli.commands:cli
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=40.8.0
  run:
    - python
    - platformdirs
    - chardet
    - click <8.4.0
    - colorama >=0.3
    - diff-cover >=2.5.0
    - jinja2
    - pathspec
    - pyyaml >=5.1
    - regex
    - tblib
    - toml   # [py<311]
    - tqdm

# Error: fixture 'test_verbosity_level' not found
{% set deselect_tests = " --deselect=test/testing_test.py::test_rules_test_case_has_variable_introspection" %}

test:
  source_files:
    - test
  imports:
    - sqlfluff
  commands:
    - pip check
    - sqlfluff --help
    - pytest -vvv test {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://www.sqlfluff.com
  summary: The SQL Linter for Humans
  dev_url: https://github.com/sqlfluff/sqlfluff
  doc_url: https://docs.sqlfluff.com/en/stable/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  description: |
    SQLFluff is a dialect-flexible and configurable SQL linter. Designed
     with ELT applications in mind, SQLFluff also works with Jinja
     templating and dbt. SQLFluff will auto-fix most linting errors,
     allowing you to focus your time on what matters.

extra:
  recipe-maintainers:
    - svengiegerich
    - borchero
    - thewchan
