{% set name = "sqlfluff" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlfluff-{{ version }}.tar.gz
  sha256: 2c597a2c8dbe50893dc2364ebf0338b0847cd4137ef6798c1529f23c63219f58

build:
  noarch: python
  number: 0
  entry_points:
    - sqlfluff = sqlfluff.cli.commands:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - cached-property
    - chardet
    - click >=7.1
    - colorama >=0.3
    - configparser
    - dataclasses
    - diff-cover >=2.5.0
    - jinja2
    - oyaml
    - pathspec
    - pluggy
    - pytest
    - python >=3.6
    - tblib
    - toml
    - typing_extensions

test:
  imports:
    - sqlfluff
    - sqlfluff.api
  commands:
    - pip check
    - sqlfluff --help
  requires:
    - pip

about:
  home: https://www.sqlfluff.com/
  summary: The SQL Linter for Humans
  dev_url: https://github.com/sqlfluff/sqlfluff
  doc_url: https://docs.sqlfluff.com/en/stable/index.html
  license: MIT
  license_file: LICENSE.md
  description: |
    SQLFluff is a dialect-flexible and configurable SQL linter. Designed
     with ELT applications in mind, SQLFluff also works with Jinja
     templating and dbt. SQLFluff will auto-fix most linting errors,
     allowing you to focus your time on what matters.

extra:
  recipe-maintainers:
    - thewchan
